#!/usr/bin/env python3
"""Package V5.2 keystore2 as an isolated recovery runtime.

The historical filename is retained so existing workflow links remain valid.

The input is a built recovery root.  The output is deliberately split into:

* ``install-root``: files that may be overlaid into the hybrid ramdisk; and
* ``context-shim``: exact stock-type fragments that must be merged, never used
  as whole-file replacements; and
* ``reference-contexts``: source-policy evidence which MUST NOT be installed.

Only the keystore2 entry point has its PT_INTERP payload changed.  Its matching
dynamic linker and the exact recursive 64-bit DT_NEEDED closure are copied
byte-for-byte into /system/tw.  This file intentionally uses only Python's
standard library so it can run in a clean GitHub Actions checkout.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import struct
import tempfile
import xml.etree.ElementTree as ET
from collections import defaultdict, deque
from dataclasses import dataclass
from pathlib import Path, PurePosixPath


PRIVATE_INTERPRETER = "/system/tw/linker64"
SOURCE_EXECUTABLE = "system/bin/keystore2"
TARGET_EXECUTABLE = "system/tw/bin/keystore2"
TARGET_LINKER = "system/tw/linker64"
TARGET_LIBRARY_DIRECTORY = "system/tw/lib64"
TARGET_INIT = "system/etc/init/keystore2.rc"
TARGET_VINTF = "system/etc/vintf/manifest/android.system.keystore2-service.xml"
SERVICE_CONTEXT_TARGET = "system/etc/selinux/plat_service_contexts"
KEY_CONTEXT_TARGET = "system/etc/selinux/plat_keystore2_key_contexts"
COMPANION_PERMISSION_PATCH = "H40_RECOVERY_KEYSTORE2_PERMISSION_SHIM_V51"
PINNED_KEYSTORE2_SOURCE_COMMIT = "14737db1429b8eebc15568bc748b2cd79ccad5c2"
BINDER_COMPATIBILITY_MARKER = "H40_RECOVERY_BINDER_STABILITY_V0_V52"
PINNED_FRAMEWORKS_NATIVE_COMMIT = "89c808424fbce9e40c0d4e0d1920b3c64a191b7f"
UNPATCHED_V51_LIBBINDER_SHA256 = (
    "3c5e1682f1fcf1a9c064decd2df5a0b30b5756a5b67c5c1d47884e3f1140ba56"
)

KEYSTORE2_BINDER_SERVICES = (
    "android.system.keystore2.IKeystoreService/default",
    "android.security.apc",
    "android.security.authorization",
    "android.security.compat",
    "android.security.metrics",
    "android.security.remoteprovisioning",
    "android.security.maintenance",
    "android.security.legacykeystore",
)
STOCK_COMPATIBILITY_CONTEXT = "u:object_r:keystore_service:s0"

DT_NULL = 0
DT_NEEDED = 1
DT_STRTAB = 5
DT_STRSZ = 10
DT_SONAME = 14
DT_RPATH = 15
DT_RUNPATH = 29
PT_LOAD = 1
PT_DYNAMIC = 2
PT_INTERP = 3

LIBRARY_DIRECTORIES = (
    "system/lib64",
    "system/system/lib64",
    "system_ext/lib64",
    "system/system_ext/lib64",
    "product/lib64",
    "system/product/lib64",
    "vendor/lib64",
    "system/vendor/lib64",
    "odm/lib64",
    "vendor/odm/lib64",
)

VINTF_CANDIDATES = (
    "system/etc/vintf/manifest/android.system.keystore2-service.xml",
    "system/etc/vintf/android.system.keystore2-service.xml",
)

REFERENCE_CONTEXT_SPECS = (
    ("file_contexts", r"keystore2|/system/bin/keystore|keystore_exec"),
    ("plat_file_contexts", r"keystore2|/system/bin/keystore|keystore_exec"),
    (
        "system/etc/selinux/plat_service_contexts",
        r"keystore|authorization|keymint|secureclock|sharedsecret",
    ),
    ("system/etc/selinux/plat_hwservice_contexts", r"keymaster|keymint|secureclock"),
    ("system/etc/selinux/plat_keystore2_key_contexts", None),
)

SERVICE_TEXT = """# Generated by package-h40-v51-keystore2-runtime.py.
# The preserved ColorOS init mounts /tmp but omits TWRP's keystore paths.
on init
    mkdir /tmp/misc
    mkdir /tmp/misc/keystore/

# Deliberately disabled: the H.40 adapter starts this service only when a
# credential must be verified.  Do not add an automatic start trigger.
service keystore2 /system/tw/bin/keystore2 /tmp/misc/keystore
    class early_hal
    user root
    group keystore readproc log
    disabled
    seclabel u:r:recovery:s0
"""

TOP_README = f"""H.40 V5.2 private keystore2 runtime

Copy files below install-root to their corresponding absolute paths.  Apply the
two context-shim fragments using the exact merge operations in MANIFEST.json;
never replace a complete stock context file with a fragment.  The separate
reference-contexts directory is evidence only and must never be installed.

Integration preconditions:
1. /system/tw/bin must select /system/tw/lib64 in the active linker config.
2. Any other init service named keystore2 must be removed/replaced; duplicate
   service definitions are rejected by Android init.
3. Keep the stock recovery policy/contexts.  The service deliberately runs in
   u:r:recovery:s0; reference mappings may not exist in the stock policy.
4. Merge the VINTF fragment only when the active manifest does not already
   declare android.system.keystore2.IKeystoreService/default.
5. Private libbinder must contain {BINDER_COMPATIBILITY_MARKER} from pinned
   frameworks/native {PINNED_FRAMEWORKS_NATIVE_COMMIT}; never replace the stock
   /system/lib64/libbinder.so.
6. The context shim requires source marker {COMPANION_PERMISSION_PATCH}; stock
   deny_unknown makes the absent keystore2_key class fail even when every label
   type exists.
"""

REFERENCE_README = """REFERENCE ONLY - DO NOT INSTALL

These are narrowly filtered lines copied from the recovery build input.  They
help audit Binder/service/key context expectations, but they are not proof that
the stock ColorOS recovery policy defines the same types or permits the same
operations.  Installing these text files without the matching compiled policy
can make init/service-manager labeling fail.  V5.2 therefore does not place any
of them below install-root and does not assert new stock-policy labels.
"""

SERVICE_CONTEXT_SHIM = "".join(
    f"{name:<68} {STOCK_COMPATIBILITY_CONTEXT}\n" for name in KEYSTORE2_BINDER_SERVICES
)
KEY_CONTEXT_SHIM = f"103            {STOCK_COMPATIBILITY_CONTEXT}\n"
CONTEXT_SHIM_REQUIREMENT = f"""required_companion_marker={COMPANION_PERMISSION_PATCH}
required_keystore2_source_commit={PINNED_KEYSTORE2_SOURCE_COMMIT}
mandatory=true
reason=stock policy uses deny_unknown and has no keystore2_key class; context text alone cannot authorize the namespace permission check
"""
CONTEXT_SHIM_README = f"""H.40 recovery-only keystore2 compatibility context shim

This directory contains merge fragments, not replacements for the stock files.
The installer must preserve every unrelated stock line and apply only the exact
names below.  Both targets have mode 0644.

Service fragment target: {SERVICE_CONTEXT_TARGET}
Operation: replace conflicting entries for the eight exact names, then insert
the fragment before the wildcard fallback.  Preserve every other stock entry.

Key fragment target: {KEY_CONTEXT_TARGET}
Operation: replace conflicting namespace 103, or create the file when absent.
Preserve every other stock namespace.

Every emitted label uses the stock-known type keystore_service.  No full TWRP
context file and no TWRP-only policy type is imported.

MANDATORY COMPANION SOURCE MARKER: {COMPANION_PERMISSION_PATCH}
Pinned TeamWin system/security source: {PINNED_KEYSTORE2_SOURCE_COMMIT}
The stock ColorOS compiled policy uses deny_unknown and does not define the
keystore2_key class.  Therefore these mappings cannot make the namespace check
pass by themselves.  Install them only with the companion source patch, whose
bypass is constrained to recovery and the locksettings namespace 103.
"""


class PackageError(RuntimeError):
    """A deterministic packaging or verification invariant failed."""


def fail(message: str) -> None:
    raise PackageError(message)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        while True:
            chunk = stream.read(1024 * 1024)
            if not chunk:
                return digest.hexdigest()
            digest.update(chunk)


def safe_dependency_name(name: str) -> str:
    if not name or PurePosixPath(name).name != name or name in {".", ".."}:
        fail(f"unsafe DT_NEEDED name: {name!r}")
    if "\\" in name or "\x00" in name:
        fail(f"unsafe DT_NEEDED name: {name!r}")
    return name


@dataclass(frozen=True)
class ProgramHeader:
    kind: int
    offset: int
    vaddr: int
    filesz: int


@dataclass(frozen=True)
class ElfInfo:
    path: Path
    bits: int
    encoding: int
    endian: str
    machine: int
    interpreter: str | None
    interpreter_offset: int | None
    interpreter_size: int | None
    needed: tuple[str, ...]
    soname: str | None
    rpath: str | None
    runpath: str | None


def unpack(data: bytes, endian: str, fmt: str, offset: int) -> tuple[int, ...]:
    size = struct.calcsize(endian + fmt)
    if offset < 0 or offset + size > len(data):
        fail(f"truncated ELF structure at {offset:#x}")
    return struct.unpack_from(endian + fmt, data, offset)


def c_string(table: bytes, offset: int, description: str) -> str:
    if offset < 0 or offset >= len(table):
        fail(f"invalid {description} string offset {offset:#x}")
    end = table.find(b"\x00", offset)
    if end < 0:
        fail(f"unterminated {description} string")
    try:
        return table[offset:end].decode("ascii")
    except UnicodeDecodeError as exc:
        raise PackageError(f"non-ASCII {description} string") from exc


def parse_elf(path: Path) -> ElfInfo:
    try:
        data = path.read_bytes()
    except OSError as exc:
        raise PackageError(f"cannot read {path}: {exc}") from exc
    if data[:4] != b"\x7fELF":
        fail(f"not an ELF file: {path}")
    elf_class, encoding = data[4], data[5]
    if elf_class not in (1, 2) or encoding not in (1, 2):
        fail(f"unsupported ELF class/encoding: {path}")
    bits = 32 if elf_class == 1 else 64
    endian = "<" if encoding == 1 else ">"
    if bits == 64:
        header = unpack(data, endian, "HHIQQQIHHHHHH", 16)
        phoff, phentsize, phnum = header[4], header[8], header[9]
        ph_format = "IIQQQQQQ"
    else:
        header = unpack(data, endian, "HHIIIIIHHHHHH", 16)
        phoff, phentsize, phnum = header[4], header[8], header[9]
        ph_format = "IIIIIIII"
    machine = header[1]

    headers: list[ProgramHeader] = []
    interpreter_rows: list[tuple[int, int]] = []
    for number in range(phnum):
        row_offset = phoff + number * phentsize
        values = unpack(data, endian, ph_format, row_offset)
        if bits == 64:
            kind, file_offset, vaddr, filesz = values[0], values[2], values[3], values[5]
        else:
            kind, file_offset, vaddr, filesz = values[0], values[1], values[2], values[4]
        if file_offset + filesz > len(data):
            fail(f"program header exceeds file: {path}")
        headers.append(ProgramHeader(kind, file_offset, vaddr, filesz))
        if kind == PT_INTERP:
            interpreter_rows.append((file_offset, filesz))
    if len(interpreter_rows) > 1:
        fail(f"multiple PT_INTERP segments: {path}")

    interpreter = None
    interpreter_offset = None
    interpreter_size = None
    if interpreter_rows:
        interpreter_offset, interpreter_size = interpreter_rows[0]
        segment = data[interpreter_offset : interpreter_offset + interpreter_size]
        if not segment.endswith(b"\x00"):
            fail(f"PT_INTERP is not NUL-terminated: {path}")
        try:
            interpreter = segment.split(b"\x00", 1)[0].decode("ascii")
        except UnicodeDecodeError as exc:
            raise PackageError(f"non-ASCII PT_INTERP: {path}") from exc

    def vaddr_to_offset(address: int) -> int:
        for ph in headers:
            if ph.kind != PT_LOAD:
                continue
            if ph.vaddr <= address < ph.vaddr + ph.filesz:
                return ph.offset + address - ph.vaddr
        fail(f"dynamic string table is not file-backed: {path}")
        raise AssertionError("unreachable")

    dynamic: list[tuple[int, int]] = []
    dynamic_size = 16 if bits == 64 else 8
    dynamic_format = "qQ" if bits == 64 else "iI"
    for ph in headers:
        if ph.kind != PT_DYNAMIC:
            continue
        if ph.filesz % dynamic_size:
            fail(f"misaligned PT_DYNAMIC segment: {path}")
        for offset in range(ph.offset, ph.offset + ph.filesz, dynamic_size):
            tag, value = unpack(data, endian, dynamic_format, offset)
            if tag == DT_NULL:
                break
            dynamic.append((tag, value))
    by_tag: dict[int, list[int]] = defaultdict(list)
    for tag, value in dynamic:
        by_tag[tag].append(value)
    string_table = b""
    if dynamic:
        if DT_STRTAB not in by_tag or DT_STRSZ not in by_tag:
            fail(f"dynamic ELF has no complete string table: {path}")
        string_offset = vaddr_to_offset(by_tag[DT_STRTAB][0])
        string_size = by_tag[DT_STRSZ][0]
        if string_offset + string_size > len(data):
            fail(f"dynamic string table exceeds file: {path}")
        string_table = data[string_offset : string_offset + string_size]

    def first_string(tag: int, description: str) -> str | None:
        values = by_tag.get(tag, [])
        if not values:
            return None
        if len(values) != 1:
            fail(f"multiple {description} entries: {path}")
        return c_string(string_table, values[0], description)

    needed = tuple(
        safe_dependency_name(c_string(string_table, value, "DT_NEEDED"))
        for value in by_tag.get(DT_NEEDED, [])
    )
    return ElfInfo(
        path=path,
        bits=bits,
        encoding=encoding,
        endian=endian,
        machine=machine,
        interpreter=interpreter,
        interpreter_offset=interpreter_offset,
        interpreter_size=interpreter_size,
        needed=needed,
        soname=first_string(DT_SONAME, "DT_SONAME"),
        rpath=first_string(DT_RPATH, "DT_RPATH"),
        runpath=first_string(DT_RUNPATH, "DT_RUNPATH"),
    )


def patch_interpreter(path: Path, elf: ElfInfo) -> tuple[bytes, dict[str, object]]:
    if elf.interpreter != "/system/bin/linker64":
        fail(f"unexpected keystore2 PT_INTERP: {elf.interpreter!r}")
    if elf.interpreter_offset is None or elf.interpreter_size is None:
        fail("keystore2 has no PT_INTERP")
    source = path.read_bytes()
    replacement = PRIVATE_INTERPRETER.encode("ascii") + b"\x00"
    if len(replacement) > elf.interpreter_size:
        fail("private PT_INTERP does not fit the source segment")
    offset, size = elf.interpreter_offset, elf.interpreter_size
    patched = bytearray(source)
    patched[offset : offset + size] = replacement + b"\x00" * (size - len(replacement))
    if patched[:offset] != source[:offset] or patched[offset + size :] != source[offset + size :]:
        fail("bytes outside PT_INTERP changed")
    return bytes(patched), {
        "original_interpreter": elf.interpreter,
        "private_interpreter": PRIVATE_INTERPRETER,
        "pt_interp_offset": offset,
        "pt_interp_size": size,
        "source_sha256": sha256(source),
        "output_sha256": sha256(bytes(patched)),
        "bytes_outside_pt_interp_unchanged": True,
    }


@dataclass
class SelectedLibrary:
    needed_name: str
    source_relative: str
    source_path: Path
    elf: ElfInfo
    requested_by: set[str]
    alternatives: tuple[str, ...]


def iter_library_candidates(root: Path):
    for priority, relative_directory in enumerate(LIBRARY_DIRECTORIES):
        directory = root / PurePosixPath(relative_directory)
        try:
            is_directory = directory.is_dir()
        except OSError:
            # CPIO extraction on Windows can materialize Linux directory
            # symlinks which the host cannot follow.  Canonical directories
            # earlier in LIBRARY_DIRECTORIES remain independently auditable.
            is_directory = False
        if not is_directory:
            continue
        try:
            paths = sorted(directory.rglob("*"), key=lambda item: item.as_posix())
        except OSError as exc:
            raise PackageError(f"cannot enumerate library directory {directory}: {exc}") from exc
        for path in paths:
            try:
                is_file = path.is_file()
            except OSError:
                is_file = False
            if not is_file:
                continue
            try:
                with path.open("rb") as stream:
                    if stream.read(4) != b"\x7fELF":
                        continue
                elf = parse_elf(path)
            except OSError as exc:
                raise PackageError(f"cannot inspect {path}: {exc}") from exc
            yield priority, path.relative_to(root).as_posix(), path, elf


def resolve_closure(root: Path, executable: ElfInfo) -> dict[str, SelectedLibrary]:
    index: dict[str, list[tuple[int, str, Path, ElfInfo]]] = defaultdict(list)
    for row in iter_library_candidates(root):
        priority, relative, path, elf = row
        index[path.name].append(row)
        if elf.soname and elf.soname != path.name:
            index[elf.soname].append(row)
    for rows in index.values():
        rows.sort(key=lambda row: (row[0], len(row[1]), row[1]))

    selected: dict[str, SelectedLibrary] = {}
    queue = deque((name, SOURCE_EXECUTABLE) for name in executable.needed)
    while queue:
        name, requester = queue.popleft()
        safe_dependency_name(name)
        if name in selected:
            selected[name].requested_by.add(requester)
            continue
        candidates = index.get(name, [])
        if not candidates:
            fail(f"missing DT_NEEDED {name!r}, requested by {requester}")
        minimum_priority = candidates[0][0]
        peers = [row for row in candidates if row[0] == minimum_priority]
        peer_hashes = {file_sha256(row[2]) for row in peers}
        if len(peer_hashes) != 1:
            fail(
                f"ambiguous same-priority candidates for {name!r}: "
                + ", ".join(row[1] for row in peers)
            )
        priority, relative, path, elf = peers[0]
        del priority
        if elf.bits != executable.bits or elf.encoding != executable.encoding or elf.machine != executable.machine:
            fail(f"ABI mismatch for {name!r}: {relative}")
        if elf.interpreter is not None:
            fail(f"DT_NEEDED candidate unexpectedly has PT_INTERP: {relative}")
        alternatives = tuple(row[1] for row in candidates[1:])
        selected[name] = SelectedLibrary(name, relative, path, elf, {requester}, alternatives)
        for child in elf.needed:
            queue.append((child, name))
    return selected


def write_file(path: Path, data: bytes, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    try:
        path.chmod(mode)
    except OSError as exc:
        raise PackageError(f"cannot set mode on {path}: {exc}") from exc


def validate_vintf(data: bytes) -> None:
    try:
        root = ET.fromstring(data)
    except ET.ParseError as exc:
        raise PackageError(f"invalid keystore2 VINTF fragment: {exc}") from exc
    if root.tag != "manifest" or root.attrib.get("type") != "framework":
        fail("keystore2 VINTF fragment is not a framework manifest")
    found = False
    for hal in root.findall("hal"):
        if hal.attrib.get("format") != "aidl" or hal.findtext("name") != "android.system.keystore2":
            continue
        for interface in hal.findall("interface"):
            if interface.findtext("name") != "IKeystoreService":
                continue
            if any(instance.text == "default" for instance in interface.findall("instance")):
                found = True
    if not found:
        fail("VINTF fragment lacks android.system.keystore2.IKeystoreService/default")


def copy_vintf(root: Path, install_root: Path) -> dict[str, object]:
    for candidate in VINTF_CANDIDATES:
        source = root / PurePosixPath(candidate)
        if source.is_file():
            data = source.read_bytes()
            validate_vintf(data)
            target = install_root / PurePosixPath(TARGET_VINTF)
            write_file(target, data, 0o644)
            return {
                "source": candidate,
                "target": TARGET_VINTF,
                "bytes": len(data),
                "sha256": sha256(data),
            }
    fail("keystore2 VINTF fragment is missing from recovery root")
    raise AssertionError("unreachable")


def write_reference_contexts(root: Path, output: Path) -> list[dict[str, object]]:
    reference_root = output / "reference-contexts"
    write_file(reference_root / "README.txt", REFERENCE_README.encode("utf-8"), 0o644)
    records = []
    for relative, pattern in REFERENCE_CONTEXT_SPECS:
        source = root / PurePosixPath(relative)
        if not source.is_file():
            continue
        text = source.read_text(encoding="utf-8", errors="strict")
        if pattern is None:
            selected_lines = text.splitlines()
        else:
            matcher = re.compile(pattern, re.IGNORECASE)
            selected_lines = [line for line in text.splitlines() if matcher.search(line)]
        if not selected_lines:
            continue
        data = ("\n".join(selected_lines) + "\n").encode("utf-8")
        target_name = relative.replace("/", "__") + ".reference.txt"
        target = reference_root / target_name
        write_file(target, data, 0o644)
        records.append(
            {
                "source": relative,
                "target": f"reference-contexts/{target_name}",
                "lines": len(selected_lines),
                "bytes": len(data),
                "sha256": sha256(data),
                "install": False,
            }
        )
    if not records:
        fail("no keystore2-related context reference material found")
    return records


def write_context_shim(output: Path) -> dict[str, object]:
    """Write minimal merge fragments; never copy the build's full contexts."""

    shim_root = output / "context-shim"
    files = (
        ("README.txt", CONTEXT_SHIM_README.encode("utf-8")),
        ("REQUIRES.txt", CONTEXT_SHIM_REQUIREMENT.encode("utf-8")),
        ("plat_service_contexts.merge", SERVICE_CONTEXT_SHIM.encode("utf-8")),
        ("plat_keystore2_key_contexts.merge", KEY_CONTEXT_SHIM.encode("utf-8")),
    )
    records = []
    for name, data in files:
        write_file(shim_root / name, data, 0o644)
        records.append(
            {
                "path": f"context-shim/{name}",
                "bytes": len(data),
                "sha256": sha256(data),
                "artifact_mode": "0644",
            }
        )
    return {
        "install": True,
        "install_method": "deterministic merge; never replace a complete stock context file",
        "stock_known_type": "keystore_service",
        "stock_known_context": STOCK_COMPATIBILITY_CONTEXT,
        "required_companion_patch": {
            "source_marker": COMPANION_PERMISSION_PATCH,
            "pinned_source_commit": PINNED_KEYSTORE2_SOURCE_COMMIT,
            "mandatory": True,
            "reason": "stock deny_unknown blocks checks for the absent keystore2_key class",
            "scope_required": "recovery-only, namespace 103 only",
        },
        "operations": [
            {
                "source": "context-shim/plat_service_contexts.merge",
                "target": SERVICE_CONTEXT_TARGET,
                "mode": "0644",
                "operation": "replace-or-insert exact names before wildcard; preserve all unrelated stock lines",
                "exact_names": list(KEYSTORE2_BINDER_SERVICES),
            },
            {
                "source": "context-shim/plat_keystore2_key_contexts.merge",
                "target": KEY_CONTEXT_TARGET,
                "mode": "0644",
                "operation": "replace-or-insert exact namespace; preserve all unrelated stock lines",
                "exact_namespaces": [103],
            },
        ],
        "files": records,
    }


def listed_files(root: Path, exclude: set[str] | None = None) -> list[dict[str, object]]:
    excluded = exclude or set()
    rows = []
    for path in sorted((item for item in root.rglob("*") if item.is_file()), key=lambda item: item.as_posix()):
        relative = path.relative_to(root).as_posix()
        if relative in excluded:
            continue
        rows.append(
            {
                "path": relative,
                "bytes": path.stat().st_size,
                "sha256": file_sha256(path),
            }
        )
    return rows


def normalize_mtimes(root: Path, epoch: int) -> None:
    for path in sorted(root.rglob("*"), key=lambda item: item.as_posix(), reverse=True):
        if path.is_dir():
            path.chmod(0o755)
        # The output contains no symlinks.  Avoid follow_symlinks=False because
        # the bundled Windows Python runtime does not implement that variant.
        os.utime(path, (epoch, epoch))
    root.chmod(0o755)
    os.utime(root, (epoch, epoch))


def verify_service(data: str) -> None:
    expected_init = "on init\n    mkdir /tmp/misc\n    mkdir /tmp/misc/keystore/\n"
    expected_header = "service keystore2 /system/tw/bin/keystore2 /tmp/misc/keystore"
    if expected_header not in data:
        fail("private keystore2 service header is wrong")
    if data.count(expected_init) != 1 or data.index(expected_init) > data.index(expected_header):
        fail("private keystore2 database-directory init action is missing or misplaced")
    stanza = data.split(expected_header, 1)[1]
    if not re.search(r"(?m)^\s+disabled\s*$", stanza):
        fail("private keystore2 service is not disabled")
    if not re.search(r"(?m)^\s+seclabel u:r:recovery:s0\s*$", stanza):
        fail("private keystore2 service does not use recovery seclabel")
    if re.findall(r"(?m)^\s*on\s+.*$", data) != ["on init"]:
        fail("private keystore2 init fragment has an unexpected trigger")
    if re.search(r"(?m)^\s*start\s+keystore2\s*$", data):
        fail("private keystore2 service has a forbidden automatic start trigger")


def verify_context_shim(output: Path, manifest: dict[str, object]) -> None:
    shim_root = output / "context-shim"
    expected = {
        "README.txt": CONTEXT_SHIM_README.encode("utf-8"),
        "REQUIRES.txt": CONTEXT_SHIM_REQUIREMENT.encode("utf-8"),
        "plat_service_contexts.merge": SERVICE_CONTEXT_SHIM.encode("utf-8"),
        "plat_keystore2_key_contexts.merge": KEY_CONTEXT_SHIM.encode("utf-8"),
    }
    if not shim_root.is_dir():
        fail("installable compatibility context shim is missing")
    actual_names = sorted(path.name for path in shim_root.iterdir() if path.is_file())
    if actual_names != sorted(expected):
        fail(f"context shim file set is not exact: {actual_names}")
    for name, data in expected.items():
        path = shim_root / name
        if path.read_bytes() != data:
            fail(f"context shim content mismatch: {name}")
        # chmod has only a read-only-bit model on Windows.  CI/repack runs on
        # Linux, where the exact emitted mode is enforced here.
        if os.name == "posix" and (path.stat().st_mode & 0o7777) != 0o644:
            fail(f"context shim mode is not 0644: {name}")

    service_rows = [line.split() for line in SERVICE_CONTEXT_SHIM.splitlines() if line.strip()]
    if [row[0] for row in service_rows] != list(KEYSTORE2_BINDER_SERVICES):
        fail("context shim Binder service set/order changed")
    if any(len(row) != 2 or row[1] != STOCK_COMPATIBILITY_CONTEXT for row in service_rows):
        fail("context shim uses a non-stock Binder label")
    key_rows = [line.split() for line in KEY_CONTEXT_SHIM.splitlines() if line.strip()]
    if key_rows != [["103", STOCK_COMPATIBILITY_CONTEXT]]:
        fail("context shim is not the exact namespace-103 mapping")

    shim_manifest = manifest.get("compatibility_context_shim")
    if not isinstance(shim_manifest, dict) or shim_manifest.get("install") is not True:
        fail("manifest does not mark compatibility context shim installable")
    dependency = shim_manifest.get("required_companion_patch")
    if not isinstance(dependency, dict):
        fail("context shim companion-patch dependency is missing")
    if (
        dependency.get("source_marker") != COMPANION_PERMISSION_PATCH
        or dependency.get("pinned_source_commit") != PINNED_KEYSTORE2_SOURCE_COMMIT
        or dependency.get("mandatory") is not True
    ):
        fail("context shim companion-patch dependency is not exact/mandatory")
    operations = shim_manifest.get("operations")
    if not isinstance(operations, list) or len(operations) != 2:
        fail("context shim must have exactly two merge operations")
    expected_targets = [SERVICE_CONTEXT_TARGET, KEY_CONTEXT_TARGET]
    if [row.get("target") for row in operations] != expected_targets:
        fail("context shim merge targets changed")
    if any(row.get("mode") != "0644" for row in operations):
        fail("context shim target mode is not exactly 0644")

    serialized = SERVICE_CONTEXT_SHIM + KEY_CONTEXT_SHIM
    forbidden_types = (
        "authorization_service",
        "legacykeystore_service",
        "keystore_maintenance_service",
        "keystore_metrics_service",
        "locksettings_key",
        "keystore2_key",
    )
    if any(name in serialized for name in forbidden_types):
        fail("context shim imported a TWRP-only policy type")


def verify_package(output: Path) -> dict[str, object]:
    manifest_path = output / "MANIFEST.json"
    sums_path = output / "SHA256SUMS"
    if not manifest_path.is_file() or not sums_path.is_file():
        fail("package manifest/hash list is missing")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("format") != 1:
        fail("unsupported package manifest format")
    verify_context_shim(output, manifest)
    install_root = output / "install-root"
    executable_path = install_root / PurePosixPath(TARGET_EXECUTABLE)
    linker_path = install_root / PurePosixPath(TARGET_LINKER)
    executable = parse_elf(executable_path)
    linker = parse_elf(linker_path)
    if executable.bits != 64 or executable.interpreter != PRIVATE_INTERPRETER:
        fail("packaged keystore2 is not an ELF64 private-runtime executable")
    if linker.bits != 64 or linker.interpreter is not None:
        fail("packaged private linker is invalid")
    if (linker.encoding, linker.machine) != (executable.encoding, executable.machine):
        fail("packaged linker ABI does not match keystore2")

    library_root = install_root / PurePosixPath(TARGET_LIBRARY_DIRECTORY)
    libraries: dict[str, ElfInfo] = {}
    for path in sorted(library_root.glob("*"), key=lambda item: item.name):
        if not path.is_file() or PurePosixPath(path.name).name != path.name:
            fail(f"invalid private library path: {path}")
        parsed = parse_elf(path)
        if parsed.interpreter is not None or parsed.bits != 64:
            fail(f"invalid private library: {path.name}")
        libraries[path.name] = parsed
    selected: set[str] = set()
    queue = deque(executable.needed)
    while queue:
        name = queue.popleft()
        if name in selected:
            continue
        parsed = libraries.get(name)
        if parsed is None:
            fail(f"packaged recursive dependency is missing: {name}")
        selected.add(name)
        queue.extend(parsed.needed)
    extras = sorted(set(libraries) - selected)
    if extras:
        fail(f"private library directory has non-closure files: {extras}")

    private_libbinder_path = library_root / "libbinder.so"
    if not private_libbinder_path.is_file():
        fail("packaged private closure does not contain libbinder.so")
    private_libbinder_data = private_libbinder_path.read_bytes()
    private_libbinder_sha256 = sha256(private_libbinder_data)
    if BINDER_COMPATIBILITY_MARKER.encode("ascii") not in private_libbinder_data:
        fail("packaged private libbinder lacks the V5.2 SDK30 stability bridge")
    if private_libbinder_sha256 == UNPATCHED_V51_LIBBINDER_SHA256:
        fail("packaged private libbinder is still the unpatched V5.1 binary")
    binder_manifest = manifest.get("runtime", {}).get("binder_compatibility")
    if not isinstance(binder_manifest, dict):
        fail("manifest lacks V5.2 Binder compatibility attestation")
    if (
        binder_manifest.get("marker") != BINDER_COMPATIBILITY_MARKER
        or binder_manifest.get("pinned_frameworks_native_commit")
        != PINNED_FRAMEWORKS_NATIVE_COMMIT
        or binder_manifest.get("private_libbinder_sha256") != private_libbinder_sha256
        or binder_manifest.get("wire_format")
        != "SDK30 raw stability values on kernel Binder only"
        or binder_manifest.get("binder_rpc_format")
        != "Android 12.1 packed Category preserved"
        or binder_manifest.get("stock_libbinder_action") != "preserve-byte-for-byte"
    ):
        fail("manifest V5.2 Binder compatibility attestation is not exact")

    service_path = install_root / PurePosixPath(TARGET_INIT)
    verify_service(service_path.read_text(encoding="utf-8"))
    validate_vintf((install_root / PurePosixPath(TARGET_VINTF)).read_bytes())
    if (install_root / "reference-contexts").exists():
        fail("reference context material escaped into install-root")
    if not (output / "reference-contexts" / "README.txt").is_file():
        fail("reference context segregation warning is missing")

    actual_rows = listed_files(output, {"MANIFEST.json", "SHA256SUMS"})
    expected_rows = manifest.get("files")
    if actual_rows != expected_rows:
        fail("manifest file inventory/hash mismatch")
    expected_sums = "".join(f"{row['sha256']}  {row['path']}\n" for row in actual_rows)
    if sums_path.read_text(encoding="ascii") != expected_sums:
        fail("SHA256SUMS mismatch")
    manifest_library_names = {row["needed_name"] for row in manifest["runtime"]["libraries"]}
    if manifest_library_names != selected:
        fail("manifest recursive closure differs from packaged closure")
    return {
        "files": len(actual_rows),
        "libraries": len(selected),
        "bytes": sum(int(row["bytes"]) for row in actual_rows),
        "keystore2_sha256": file_sha256(executable_path),
        "private_libbinder_sha256": private_libbinder_sha256,
        "binder_stability_v0_bridge": True,
        "all_recursive_dependencies_present": True,
        "no_extra_private_libraries": True,
        "service_disabled": True,
        "reference_contexts_not_installable": True,
        "minimal_context_shim_exact": True,
        "context_shim_target_mode": "0644",
        "context_shim_companion_patch_mandatory": True,
        "keystore_database_directories_created_on_init": True,
    }


def build_package(recovery_root: Path, output: Path, epoch: int) -> dict[str, object]:
    recovery_root = recovery_root.resolve()
    output = output.resolve()
    if not recovery_root.is_dir():
        fail(f"recovery root is not a directory: {recovery_root}")
    if output.exists():
        fail(f"output already exists: {output}")
    output.parent.mkdir(parents=True, exist_ok=True)
    temp_path = Path(tempfile.mkdtemp(prefix=f".{output.name}.tmp-", dir=output.parent))
    try:
        install_root = temp_path / "install-root"
        source_executable_path = recovery_root / PurePosixPath(SOURCE_EXECUTABLE)
        executable = parse_elf(source_executable_path)
        if executable.bits != 64:
            fail(f"expected ELF64 keystore2, found ELF{executable.bits}")
        patched, patch_record = patch_interpreter(source_executable_path, executable)
        target_executable_path = install_root / PurePosixPath(TARGET_EXECUTABLE)
        write_file(target_executable_path, patched, 0o755)
        reparsed = parse_elf(target_executable_path)
        if reparsed.interpreter != PRIVATE_INTERPRETER:
            fail("PT_INTERP relocation did not survive output write")

        source_linker_relative = executable.interpreter.lstrip("/") if executable.interpreter else ""
        source_linker_path = recovery_root / PurePosixPath(source_linker_relative)
        linker = parse_elf(source_linker_path)
        if linker.bits != 64 or linker.interpreter is not None:
            fail("source linker64 is not a standalone ELF64 linker")
        if (linker.encoding, linker.machine) != (executable.encoding, executable.machine):
            fail("source linker64 ABI does not match keystore2")
        linker_data = source_linker_path.read_bytes()
        write_file(install_root / PurePosixPath(TARGET_LINKER), linker_data, 0o755)

        selected = resolve_closure(recovery_root, executable)
        private_libbinder = selected.get("libbinder.so")
        if private_libbinder is None:
            fail("keystore2 private closure does not contain libbinder.so")
        private_libbinder_data = private_libbinder.source_path.read_bytes()
        private_libbinder_sha256 = sha256(private_libbinder_data)
        if BINDER_COMPATIBILITY_MARKER.encode("ascii") not in private_libbinder_data:
            fail("built private libbinder lacks the V5.2 SDK30 stability bridge")
        if private_libbinder_sha256 == UNPATCHED_V51_LIBBINDER_SHA256:
            fail("built private libbinder still matches the unpatched V5.1 binary")
        library_rows = []
        for name in sorted(selected):
            item = selected[name]
            data = item.source_path.read_bytes()
            target_relative = f"{TARGET_LIBRARY_DIRECTORY}/{name}"
            write_file(install_root / PurePosixPath(target_relative), data, 0o644)
            library_rows.append(
                {
                    "needed_name": name,
                    "source": item.source_relative,
                    "target": target_relative,
                    "bytes": len(data),
                    "sha256": sha256(data),
                    "soname": item.elf.soname,
                    "direct_needed": list(item.elf.needed),
                    "requested_by": sorted(item.requested_by),
                    "lower_priority_alternatives": list(item.alternatives),
                }
            )

        service_data = SERVICE_TEXT.encode("utf-8")
        verify_service(SERVICE_TEXT)
        write_file(install_root / PurePosixPath(TARGET_INIT), service_data, 0o644)
        vintf_record = copy_vintf(recovery_root, install_root)
        reference_records = write_reference_contexts(recovery_root, temp_path)
        context_shim = write_context_shim(temp_path)
        write_file(temp_path / "README.txt", TOP_README.encode("utf-8"), 0o644)

        manifest = {
            "format": 1,
            "name": "guacamole-h40-v52-private-keystore2-runtime",
            "source_layout": "built recovery/root",
            "runtime": {
                "executable": {
                    "source": SOURCE_EXECUTABLE,
                    "target": TARGET_EXECUTABLE,
                    "bytes": len(patched),
                    "direct_needed": list(executable.needed),
                    **patch_record,
                },
                "linker": {
                    "source": source_linker_relative,
                    "target": TARGET_LINKER,
                    "bytes": len(linker_data),
                    "sha256": sha256(linker_data),
                    "interpreter": None,
                },
                "libraries": library_rows,
                "binder_compatibility": {
                    "marker": BINDER_COMPATIBILITY_MARKER,
                    "pinned_frameworks_native_commit": PINNED_FRAMEWORKS_NATIVE_COMMIT,
                    "private_libbinder_sha256": private_libbinder_sha256,
                    "wire_format": "SDK30 raw stability values on kernel Binder only",
                    "binder_rpc_format": "Android 12.1 packed Category preserved",
                    "stock_libbinder_action": "preserve-byte-for-byte",
                },
                "init_service": {
                    "target": TARGET_INIT,
                    "name": "keystore2",
                    "executable": "/system/tw/bin/keystore2",
                    "database_directory": "/tmp/misc/keystore",
                    "database_directory_init": [
                        "mkdir /tmp/misc",
                        "mkdir /tmp/misc/keystore/",
                    ],
                    "disabled": True,
                    "seclabel": "u:r:recovery:s0",
                    "automatic_start_trigger": False,
                    "bytes": len(service_data),
                    "sha256": sha256(service_data),
                },
                "vintf": vintf_record,
            },
            "reference_contexts": {
                "install": False,
                "directory": "reference-contexts",
                "warning": "Reference evidence only; never overlay these files onto stock ColorOS policy.",
                "files": reference_records,
            },
            "compatibility_context_shim": context_shim,
            "integration_preconditions": [
                "/system/tw/bin selects /system/tw/lib64 in the active linker configuration",
                "no duplicate init service named keystore2 remains in the merged ramdisk",
                "stock compiled sepolicy and context files remain authoritative",
                "VINTF declaration is merged without creating a duplicate HAL instance",
                "init creates /tmp/misc/keystore before credential-time keystore2 start",
                f"context shim is installed only with companion marker {COMPANION_PERMISSION_PATCH}",
                f"private libbinder contains marker {BINDER_COMPATIBILITY_MARKER}",
                "stock /system/lib64/libbinder.so is preserved byte-for-byte",
            ],
            "known_risks": [
                "The daemon comes from the TWRP 12.1 build, while the tested installed port reports Android 14; persistent.sqlite compatibility remains device-test-gated.",
                "A binary-marker audit found the same from_0_to_1 migration generation and no from_1_to_2/state-column marker in both compared daemons, reducing but not proving away the database-version risk.",
                "The installed-system daemon fallback is intentionally inactive because a prefixed read-only mount does not reproduce Android linker namespaces, APEXes, absolute paths, policy, or verified-boot provenance.",
            ],
            "checks": {
                "elf64_only": True,
                "matching_linker_abi": True,
                "pt_interp_only_relocation": True,
                "exact_recursive_dt_needed_closure": True,
                "disabled_explicit_start_service": True,
                "recovery_domain_service": True,
                "reference_contexts_non_installable": True,
                "minimal_stock_type_context_shim": True,
                "context_shim_companion_patch_mandatory": True,
                "binder_stability_v0_bridge": True,
                "stock_libbinder_preservation_mandatory": True,
                "keystore_database_directories_created_on_init": True,
            },
        }
        inventory = listed_files(temp_path, {"MANIFEST.json", "SHA256SUMS"})
        manifest["files"] = inventory
        manifest_data = (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode("utf-8")
        write_file(temp_path / "MANIFEST.json", manifest_data, 0o644)
        sums_data = "".join(f"{row['sha256']}  {row['path']}\n" for row in inventory).encode("ascii")
        write_file(temp_path / "SHA256SUMS", sums_data, 0o644)
        normalize_mtimes(temp_path, epoch)
        verification = verify_package(temp_path)
        temp_path.replace(output)
        return verification
    except Exception:
        shutil.rmtree(temp_path, ignore_errors=True)
        raise


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--recovery-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--source-date-epoch",
        type=int,
        default=int(os.environ.get("SOURCE_DATE_EPOCH", "0")),
        help="mtime applied to every output path (default: SOURCE_DATE_EPOCH or 0)",
    )
    args = parser.parse_args()
    if args.source_date_epoch < 0:
        fail("SOURCE_DATE_EPOCH must be non-negative")
    try:
        report = build_package(args.recovery_root, args.output, args.source_date_epoch)
    except PackageError as exc:
        raise SystemExit(f"error: {exc}") from exc
    print(json.dumps(report, sort_keys=True))


if __name__ == "__main__":
    main()
